-- SQL Setup for Supabase - Senior Backend Security Architect (Final Verified Plan)
-- 1. Create independent tables first

CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text
);

CREATE TABLE IF NOT EXISTS public.users (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at timestamptz DEFAULT now()
);

-- 2. Create tables with dependencies

CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  price numeric,
  stock int,
  category_id bigint REFERENCES public.categories (id)
);

-- 3. ENABLE ROW LEVEL SECURITY (Deny by Default)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 4. RLS POLICIES (Strict Content Ownership)

-- Users can read their own profile (verified via auth.uid)
CREATE POLICY users_read_own ON public.users FOR SELECT 
USING (auth.uid() = id);

-- Public read access to Products/Categories
CREATE POLICY products_read_all ON public.products FOR SELECT 
USING (true);

CREATE POLICY categories_read_all ON public.categories FOR SELECT
USING (true);

-- Admin override (Database-verified identity)
CREATE POLICY admin_full_read ON public.users FOR SELECT
USING (EXISTS (
  SELECT 1 FROM public.users 
  WHERE users.id = auth.uid() AND users.role = 'admin'
));

-- 5. AUTOMATIC PROFILE CREATION (Auth -> Public Trigger)
-- This ensures every user created via Supabase Auth has a role record in public.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER; -- SECURITY DEFINER allows it to insert into protected public.users

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. SECURE RAW SQL EXECUTION SUPPORT (RPC)
-- Security Architect Standard: Execute with caller's identity session.
CREATE OR REPLACE FUNCTION public.execute_sql(sql_query text)
RETURNS SETOF json AS $$
BEGIN
    RETURN QUERY EXECUTE 'SELECT row_to_json(t) FROM (' || sql_query || ') t';
EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION 'Database Violation or Error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql SECURITY INVOKER;
